# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Sort
version:      20070404
version_from: lib/Mail/Sort.pm
installdirs:  site
requires:
    DB_File:                       1.814
    File::Path:                    1.08
    File::Slurp:                   9999.09
    File::Spec::Functions:         1.3
    FileHandle:                    2.00
    GDBM_File:                     1.08
    POSIX:                         1.03

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
